/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const BillItem = IDL.Record({
  'qty' : IDL.Nat,
  'sellingPrice' : IDL.Float64,
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'buyingPrice' : IDL.Float64,
});
export const Bill = IDL.Record({
  'customerName' : IDL.Text,
  'date' : Time,
  'totalAmount' : IDL.Float64,
  'billNumber' : IDL.Nat,
  'items' : IDL.Vec(BillItem),
});
export const PaymentRecord = IDL.Record({
  'date' : Time,
  'note' : IDL.Text,
  'amount' : IDL.Float64,
});
export const CreditCustomer = IDL.Record({
  'payments' : IDL.Vec(PaymentRecord),
  'dateCreated' : Time,
  'name' : IDL.Text,
  'totalOwed' : IDL.Float64,
  'phone' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'stockQty' : IDL.Nat,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'sellingPrice' : IDL.Float64,
  'minStockQty' : IDL.Nat,
  'category' : IDL.Text,
  'buyingPrice' : IDL.Float64,
});
export const Purchase = IDL.Record({
  'supplierName' : IDL.Text,
  'date' : Time,
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'buyingPrice' : IDL.Float64,
});
export const DashboardSummary = IDL.Record({
  'totalProducts' : IDL.Nat,
  'outstandingLoans' : IDL.Float64,
  'lowStockCount' : IDL.Nat,
  'todaysSales' : IDL.Float64,
  'inventoryValue' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addBill' : IDL.Func([Bill], [IDL.Nat], []),
  'addCreditCustomer' : IDL.Func([CreditCustomer], [], []),
  'addProduct' : IDL.Func([Product], [IDL.Nat], []),
  'addPurchase' : IDL.Func([Purchase], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAllBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
  'getAllCreditCustomers' : IDL.Func([], [IDL.Vec(CreditCustomer)], ['query']),
  'getAllCreditCustomersSortedByAmount' : IDL.Func(
      [],
      [IDL.Vec(CreditCustomer)],
      ['query'],
    ),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllProductsSorted' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllPurchases' : IDL.Func([], [IDL.Vec(Purchase)], ['query']),
  'getBill' : IDL.Func([IDL.Nat], [Bill], ['query']),
  'getDashboardSummary' : IDL.Func([Time, Time], [DashboardSummary], ['query']),
  'getLowStockProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getOutstandingCreditCustomers' : IDL.Func(
      [],
      [IDL.Vec(CreditCustomer)],
      ['query'],
    ),
  'getProduct' : IDL.Func([IDL.Nat], [Product], []),
  'recordPayment' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const BillItem = IDL.Record({
    'qty' : IDL.Nat,
    'sellingPrice' : IDL.Float64,
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'buyingPrice' : IDL.Float64,
  });
  const Bill = IDL.Record({
    'customerName' : IDL.Text,
    'date' : Time,
    'totalAmount' : IDL.Float64,
    'billNumber' : IDL.Nat,
    'items' : IDL.Vec(BillItem),
  });
  const PaymentRecord = IDL.Record({
    'date' : Time,
    'note' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const CreditCustomer = IDL.Record({
    'payments' : IDL.Vec(PaymentRecord),
    'dateCreated' : Time,
    'name' : IDL.Text,
    'totalOwed' : IDL.Float64,
    'phone' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'stockQty' : IDL.Nat,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'sellingPrice' : IDL.Float64,
    'minStockQty' : IDL.Nat,
    'category' : IDL.Text,
    'buyingPrice' : IDL.Float64,
  });
  const Purchase = IDL.Record({
    'supplierName' : IDL.Text,
    'date' : Time,
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'buyingPrice' : IDL.Float64,
  });
  const DashboardSummary = IDL.Record({
    'totalProducts' : IDL.Nat,
    'outstandingLoans' : IDL.Float64,
    'lowStockCount' : IDL.Nat,
    'todaysSales' : IDL.Float64,
    'inventoryValue' : IDL.Float64,
  });
  
  return IDL.Service({
    'addBill' : IDL.Func([Bill], [IDL.Nat], []),
    'addCreditCustomer' : IDL.Func([CreditCustomer], [], []),
    'addProduct' : IDL.Func([Product], [IDL.Nat], []),
    'addPurchase' : IDL.Func([Purchase], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAllBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
    'getAllCreditCustomers' : IDL.Func(
        [],
        [IDL.Vec(CreditCustomer)],
        ['query'],
      ),
    'getAllCreditCustomersSortedByAmount' : IDL.Func(
        [],
        [IDL.Vec(CreditCustomer)],
        ['query'],
      ),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllProductsSorted' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllPurchases' : IDL.Func([], [IDL.Vec(Purchase)], ['query']),
    'getBill' : IDL.Func([IDL.Nat], [Bill], ['query']),
    'getDashboardSummary' : IDL.Func(
        [Time, Time],
        [DashboardSummary],
        ['query'],
      ),
    'getLowStockProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getOutstandingCreditCustomers' : IDL.Func(
        [],
        [IDL.Vec(CreditCustomer)],
        ['query'],
      ),
    'getProduct' : IDL.Func([IDL.Nat], [Product], []),
    'recordPayment' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };