/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bill {
  'customerName' : string,
  'date' : Time,
  'totalAmount' : number,
  'billNumber' : bigint,
  'items' : Array<BillItem>,
}
export interface BillItem {
  'qty' : bigint,
  'sellingPrice' : number,
  'productId' : bigint,
  'productName' : string,
  'buyingPrice' : number,
}
export interface CreditCustomer {
  'payments' : Array<PaymentRecord>,
  'dateCreated' : Time,
  'name' : string,
  'totalOwed' : number,
  'phone' : string,
}
export interface DashboardSummary {
  'totalProducts' : bigint,
  'outstandingLoans' : number,
  'lowStockCount' : bigint,
  'todaysSales' : number,
  'inventoryValue' : number,
}
export interface PaymentRecord {
  'date' : Time,
  'note' : string,
  'amount' : number,
}
export interface Product {
  'id' : bigint,
  'stockQty' : bigint,
  'name' : string,
  'unit' : string,
  'sellingPrice' : number,
  'minStockQty' : bigint,
  'category' : string,
  'buyingPrice' : number,
}
export interface Purchase {
  'supplierName' : string,
  'date' : Time,
  'productId' : bigint,
  'productName' : string,
  'quantity' : bigint,
  'buyingPrice' : number,
}
export type Time = bigint;
export interface _SERVICE {
  'addBill' : ActorMethod<[Bill], bigint>,
  'addCreditCustomer' : ActorMethod<[CreditCustomer], undefined>,
  'addProduct' : ActorMethod<[Product], bigint>,
  'addPurchase' : ActorMethod<[Purchase], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllBills' : ActorMethod<[], Array<Bill>>,
  'getAllCreditCustomers' : ActorMethod<[], Array<CreditCustomer>>,
  'getAllCreditCustomersSortedByAmount' : ActorMethod<
    [],
    Array<CreditCustomer>
  >,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllProductsSorted' : ActorMethod<[], Array<Product>>,
  'getAllPurchases' : ActorMethod<[], Array<Purchase>>,
  'getBill' : ActorMethod<[bigint], Bill>,
  'getDashboardSummary' : ActorMethod<[Time, Time], DashboardSummary>,
  'getLowStockProducts' : ActorMethod<[], Array<Product>>,
  'getOutstandingCreditCustomers' : ActorMethod<[], Array<CreditCustomer>>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'recordPayment' : ActorMethod<[string, number], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];