/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BillItem {
    qty: bigint;
    sellingPrice: number;
    productId: bigint;
    productName: string;
    buyingPrice: number;
}
export type Time = bigint;
export interface CreditCustomer {
    payments: Array<PaymentRecord>;
    dateCreated: Time;
    name: string;
    totalOwed: number;
    phone: string;
}
export interface PaymentRecord {
    date: Time;
    note: string;
    amount: number;
}
export interface Bill {
    customerName: string;
    date: Time;
    totalAmount: number;
    billNumber: bigint;
    items: Array<BillItem>;
}
export interface Purchase {
    supplierName: string;
    date: Time;
    productId: bigint;
    productName: string;
    quantity: bigint;
    buyingPrice: number;
}
export interface DashboardSummary {
    totalProducts: bigint;
    outstandingLoans: number;
    lowStockCount: bigint;
    todaysSales: number;
    inventoryValue: number;
}
export interface Product {
    id: bigint;
    stockQty: bigint;
    name: string;
    unit: string;
    sellingPrice: number;
    minStockQty: bigint;
    category: string;
    buyingPrice: number;
}
export interface backendInterface {
    addBill(bill: Bill): Promise<bigint>;
    addCreditCustomer(customer: CreditCustomer): Promise<void>;
    addProduct(product: Product): Promise<bigint>;
    addPurchase(purchase: Purchase): Promise<void>;
    deleteProduct(id: bigint): Promise<void>;
    getAllBills(): Promise<Array<Bill>>;
    getAllCreditCustomers(): Promise<Array<CreditCustomer>>;
    getAllCreditCustomersSortedByAmount(): Promise<Array<CreditCustomer>>;
    getAllProducts(): Promise<Array<Product>>;
    getAllProductsSorted(): Promise<Array<Product>>;
    getAllPurchases(): Promise<Array<Purchase>>;
    getBill(billNumber: bigint): Promise<Bill>;
    getDashboardSummary(startTime: Time, endTime: Time): Promise<DashboardSummary>;
    getLowStockProducts(): Promise<Array<Product>>;
    getOutstandingCreditCustomers(): Promise<Array<CreditCustomer>>;
    getProduct(id: bigint): Promise<Product>;
    recordPayment(customerName: string, amount: number): Promise<void>;
    updateProduct(product: Product): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addBill(arg0: Bill): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addBill(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBill(arg0);
            return result;
        }
    }
    async addCreditCustomer(arg0: CreditCustomer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCreditCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCreditCustomer(arg0);
            return result;
        }
    }
    async addProduct(arg0: Product): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0);
            return result;
        }
    }
    async addPurchase(arg0: Purchase): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPurchase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPurchase(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getAllBills(): Promise<Array<Bill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBills();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBills();
            return result;
        }
    }
    async getAllCreditCustomers(): Promise<Array<CreditCustomer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCreditCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCreditCustomers();
            return result;
        }
    }
    async getAllCreditCustomersSortedByAmount(): Promise<Array<CreditCustomer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCreditCustomersSortedByAmount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCreditCustomersSortedByAmount();
            return result;
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return result;
        }
    }
    async getAllProductsSorted(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProductsSorted();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProductsSorted();
            return result;
        }
    }
    async getAllPurchases(): Promise<Array<Purchase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPurchases();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPurchases();
            return result;
        }
    }
    async getBill(arg0: bigint): Promise<Bill> {
        if (this.processError) {
            try {
                const result = await this.actor.getBill(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBill(arg0);
            return result;
        }
    }
    async getDashboardSummary(arg0: Time, arg1: Time): Promise<DashboardSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardSummary(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardSummary(arg0, arg1);
            return result;
        }
    }
    async getLowStockProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLowStockProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLowStockProducts();
            return result;
        }
    }
    async getOutstandingCreditCustomers(): Promise<Array<CreditCustomer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOutstandingCreditCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOutstandingCreditCustomers();
            return result;
        }
    }
    async getProduct(arg0: bigint): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return result;
        }
    }
    async recordPayment(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPayment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPayment(arg0, arg1);
            return result;
        }
    }
    async updateProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
